name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'v1.0.0'
        required: true
      path:
        description: 'target/name-here-*.jar'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Build jar
      run: mvn clean install
    - name: Upload jar
      uses: AButler/upload-release-assets@v2.0
      with:
        release-tag: ${{ github.event.inputs.release-tag }}
        files: ${{ github.event.inputs.path }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}